services:
  db-store:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: store_pg
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - '5434:5432'

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 3

    volumes:
      - store_db:/var/lib/postgresql/data

volumes:
  store_db: