services:
  db-store:
    image: postgres:17.5

    restart: always

    env_file:
      - .env
      -
    ports:
      - '5434:5432'
      -
    volumes:
      - store_db:/var/lib/postgresql/data

volumes:
  store_db: