[project]
name = "homework-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
    "psycopg[binary]>=3.2.9",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
